name: CI

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.3.0
      with:
        hugo-version: '0.59.1'
        extended: true
    
    - name: Build site
      run: hugo --minify

    - name: Build image
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        dockerfile: Dockerfile
        name: abogatikov/devalexb/devalexb
        registry: docker.pkg.github.com
        username: abogatikov
        password: ${{ secrets.GITHUB_TOKEN }}
        tag_names: true
